development:
  secret_key_base: d15b3f1961189011911165b366afa9c16172e17cedc3ce9b544b9f19f88aef19294b116c4e5f36f4fc110dbe1549695e803787ecfdb5adfc803f9a0242ebe94f
  aws:
    access_key_id: "AKIAJNFHQ6LEP5MUSV2A"
    secret_access_key: "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"
    s3_bucket_name: "tourbrewer2-development"
test:
  secret_key_base: ec5ff9c81eb2c990ec8f0d87aa927b3fd0dff19d1f38ec726fe2c18bcb4b08852ae8136d39dbfcc1cd5ba81b0fa59020014c56a4f2c4de44b971fbcca1739ce2
  aws:
    access_key_id: "AKIAJNFHQ6LEP5MUSV2A"
    secret_access_key: "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"
    s3_bucket_name: "tourbrewer-test"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>